### PR TITLE
added new copy about archives & link to gihub repo + gitignore for no…

### PR DESCRIPTION
**Pull request by walkerlj0**
…de files

### CODE REVIEW

**Comment by fauno** [comment]
Will we have french and arabic translations or should we use an automatic translator?

**Comment by walkerlj0** [comment]
@fauno can you either make a PR or type in a comment _exactly_ what should be in the github action workflow file?

**Comment by walkerlj0** [comment]
@fauno also just saw your comment - I would just use an automatic translator

**Comment by fauno** [comment]
> @fauno can you either make a PR or type in a comment _exactly_ what should be in the github action workflow file?

the way it is now on this repository is working ok and correctly configured!

**Comment by fauno** [comment]
@walkerlj0 i added deepl translations for french and arabic and generated the website from the source code. i'm uploading it to the other repo so you also have access

**Pull request closed without merging**
